### ISSUE TITLE
POSTPONE

### ISSUE THREAD

**Issue by drom** [drom/forth#3]
The following code:

``` forth
T{ : GT1 123 ; -> }T
T{ : GT4 POSTPONE GT1 ; IMMEDIATE -> }T
T{ : GT5 GT4 ; -> }T
T{ GT5 -> 123 }T
```

Lead to the core test failure:

``` forth
Error: in line: 647 T{ : GT5 GT4 ; -> }T  expected [ 291 ] to deeply equal [].
Error: in line: 648 T{ GT5 -> 123 }T  expected [] to deeply equal [ 291 ].
```

Other parts of the test with `POSTPONE` are passing.

``` forth
T{ : GT6 345 ; IMMEDIATE -> }T
T{ : GT7 POSTPONE GT6 ; -> }T
T{ GT7 -> 345 }T
```

and

``` forth
T{ : NOP : POSTPONE ; ; -> }T
T{ NOP NOP1 NOP NOP2 -> }T
T{ NOP1 -> }T
T{ NOP2 -> }T
```

**Comment by drom** [comment]
Here is some words from the standard:

![image](https://cloud.githubusercontent.com/assets/511872/11388254/092617c4-92e9-11e5-9bfb-9e0c5433f12a.png)

---

That was brief!

---

![image](https://cloud.githubusercontent.com/assets/511872/11388298/82124c20-92e9-11e5-9252-3cdf1cde7999.png)

---

![image](https://cloud.githubusercontent.com/assets/511872/11388303/93cfabf6-92e9-11e5-8dfc-5ed2315bf56f.png)

---

![image](https://cloud.githubusercontent.com/assets/511872/11388841/297753ac-92ef-11e5-97aa-eae82a54acc8.png)

---

![image](https://cloud.githubusercontent.com/assets/511872/11388854/4015b9e6-92ef-11e5-9730-7ca8fef3d0c5.png)

---

![image](https://cloud.githubusercontent.com/assets/511872/11388864/5bfd6e74-92ef-11e5-995a-2b8b0fe417db.png)

**Comment by larsbrinkhoff** [comment]
Wow, you have a copy of the standard?

**Comment by larsbrinkhoff** [comment]
If you have a traditional Forth with just default and immediate words, `POSTPONE FOO` should be the same as `COMPILE FOO` if `FOO` has default compilation semantics, and the same as `[COMPILE] FOO` if `FOO` is immediate.

**Comment by larsbrinkhoff** [comment]
It seems your problem is with `POSTPONE`ing non-immediate words.  If `bar` is not immediate

```
: foo   postpone bar ;
```

should have the same effect at run time as

```
: foo   ['] bar postpone literal  ['] compile, compile, ;
```

I.e. when `foo` runs, it compiles `bar` into the definition that is being compiled that time.  (If `bar` were immediate, it would be compiled into `foo` instead.)

Is your head spinning yet? ;-)

**Comment by drom** [comment]
Here is 'very helpful' description of  `COMPILE,` from the standard:

![image](https://cloud.githubusercontent.com/assets/511872/11390008/92c8191c-92fa-11e5-947d-357d0e5b2335.png)

**Comment by larsbrinkhoff** [comment]
Note: `COMPILE,` is just the same as `,` in a traditional (indirect or direct) threaded Forth.

**Comment by drom** [comment]
Yes, that is my issue. I have JS-Threaded Forth :smirk:
Looks like I need to detect if the word is `immediate` or not.
Current code is too simple:
https://github.com/drom/forth/blob/master/lib/cfg.js#L65-L74

``` js
def('postpone', function () {
        var w = this.io.word('\\s');
        var wordLink = this.O[w.toLowerCase()];
        if (wordLink) {
           this.pos.push(ast.callword(wordLink.index));
        } else {
            cxt.log('word: ' + w + ' is not defined');
            throw new Error;
        }
    }, cxt, { immediate: true });
```

**Comment by larsbrinkhoff** [comment]
I see your compiler is building JavaScript code at run time.  So `COMPILE,` should take an xt and generate code to call that xt.

`POSTPONE IF` should generate code to call `IF`.

`POSTPONE +` should generate code to generate code to call `+`.  Simple!

**Comment by drom** [comment]
That is what I am doing. But as you can see in the failing case:

``` forth
HEX
T{ : GT1 123 ; -> }T
T{ : GT4 POSTPONE GT1 ; IMMEDIATE -> }T
T{ : GT5 GT4 ; -> }T
T{ GT5 -> 123 }T
```

``` forth
SEE GT4
```

will be:

``` js
gt4: function () {
    this[152]();
}
```

Lead to the core test failure:

``` forth
Error: in line: 647 T{ : GT5 GT4 ; -> }T  expected [ 291 ] to deeply equal [].
Error: in line: 648 T{ GT5 -> 123 }T  expected [] to deeply equal [ 291 ].
```

You ca run it by yourself:
http://drom.io/forth

**Comment by drom** [comment]
The `comp.lang.forth` link: https://groups.google.com/forum/#!topic/comp.lang.forth/BlA-81dmWow

**Comment by larsbrinkhoff** [comment]
What does your `GT5` do?  It seems it doesn't leave `123` on the stack.  Why doesn't it do that?

`GT4` is an immediate word.  When `GT4` runs it should compile `GT1` into the current definition.  So `: GT5 GT4 ;` should have the same effect as `: GT5 GT1 ;`.

Also, where does `291` come from?

**Comment by drom** [comment]
`123` HEX = `291` DEC

**Comment by larsbrinkhoff** [comment]
Well, I tried http://drom.io/forth, and typed in the test code.

`see GT4` clearly shows the generated JavaScript code is wrong.

**Comment by drom** [comment]
Looks like `POSTPONE` has to check if the `WORD`, it is POSTPONing is `immediate` or not.

``` js
if (immediate) {
    compile the WORD into the current definition.
} else {
   compile the code that will compile the WORD into current definition when being executed.
}
```

**Comment by larsbrinkhoff** [comment]
Yes!

**Comment by drom** [comment]
Thanks, fixing. 7 more issue to go ;)

**Comment by drom** [comment]
``` forth
T{ : GT1 123 ; -> }T
T{ : GT4 POSTPONE GT1 ; IMMEDIATE -> }T
T{ : GT5 GT4 ; -> }T
T{ GT5 -> 123 }T
```

`GT1` is a word with default compilation semantics (i.e., you get them from Section 3.4.3.3 cited above. `POSTPONE GT1` appends the _compilation_ semantics of `GT1` to `GT4`, whereas just writing `GT1` would append the _execution_ semantics of GT1 to GT4. Or, in other words, `POSTPONE GT1` appends the appending of the execution semantics of `GT1` to `GT4`.  When `GT4` is performed in the next line, it appends the execution semantics of `GT1` to `GT5`.  And when `GT5` is performed in the next line, it performs the execution semantics of `GT1` and pushes `123` on the stack. 

 --- anton 

from here: https://groups.google.com/d/msg/comp.lang.forth/BlA-81dmWow/j81maLLaAAAJ

**Comment by drom** [comment]
``` forth
T{ : GT6 345 ; IMMEDIATE -> }T
T{ : GT7 POSTPONE GT6 ; -> }T
T{ GT7 -> 345 }T
```

`GT6` is an `immediate` word with the following _compilation semantic_ == _execution semantic_ is to push `345` to the stack.
`POSTPONE GT6` appends this _compilation / execution semantic_ of `GT6` to `GT7` by just compiling call to `GT6`.
`GT7` just executes this call.

``` forth
T{ : NOP : POSTPONE ; ; -> }T
T{ NOP NOP1 NOP NOP2 -> }T
T{ NOP1 -> }T
T{ NOP2 -> }T
```

`;` is an `immediate` word with the following _compilation semantic_ == _execution semantic_ of finishing the colon definition.
`POSTPONE ;` appends this _compilation / execution semantic_ of `;` to `NOP` by just compiling call to `;`.
`NOP NOP1` just executes this call.
